Feat/main page
Rainbowhorseproduction/aviasales-demo-frontend pull request #1
Opened 2018-02-14 08:27 UTC by Rainbowhorseproduction

2018-02-14 20:21 UTC, evgenyrodionov commented
https://zxl634kqvm.codesandbox.io/

![image](https://user-images.githubusercontent.com/775692/36226046-c46ada5e-11dd-11e8-919a-7428da18f5e7.png)

2018-02-16 02:39 UTC, Rainbowhorseproduction commented
Мобильная версия завершена.

2018-02-16 20:58 UTC, evgenyrodionov commented
https://codesandbox.io/s/github/Rainbowhorseproduction/aviasales-demo-frontend/tree/feat%2Fmain-page

2018-02-16 20:58 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/36328984-48e0254e-1375-11e8-9852-7e9589d33955.png)

2018-02-16 21:01 UTC, evgenyrodionov commented
Что этот файл делает в репозитории?
https://github.com/Rainbowhorseproduction/aviasales-demo-frontend/blob/9340205d61537e027ce5a6bc8bf76ca8c8ad2ec9/aviasales-demo-frontend.zip

2018-02-16 21:10 UTC, imevro requested changes
читай частые ошибки

2018-02-16 21:10 UTC, evgenyrodionov commented on src/BuyAdvices/AdviceCard.js
> +const Article = styled.div`
htmlreference.io/element/article

2018-02-16 21:10 UTC, evgenyrodionov commented on src/BuyAdvices/AdviceCard.js
> +const DetailsButton = styled.span`
button = span? это как?

2018-02-16 21:10 UTC, evgenyrodionov commented on src/BuyAdvices/dog.svg
> +<image id="image0" width="16" height="15" preserveAspectRatio="none" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAQAAABHeoekAAAM82lDQ1BrQ0dDb2xvclNwYWNlR2VuZXJpY0dyYXlHYW1tYTJf
![image](https://user-images.githubusercontent.com/775692/36329210-2d24b058-1376-11e8-9ae1-a9844a7ca012.png)

2018-02-16 21:10 UTC, evgenyrodionov commented on src/BuyAdvices/index.js
> +        topic={"КАК КУПИТЬ ДЕШЕВЫЕ АВИАБИЛЕТЫ?"}
текст передается как обычный хтмл-атрибут

2018-02-16 21:10 UTC, evgenyrodionov commented on src/CityAdvertisings/CityCard.js
> +const Col = styled.div`
не используй имена, которые могут пересекаться с сеткой

2018-02-16 21:10 UTC, evgenyrodionov commented on src/CityAdvertisings/CityCard.js
> +const Date = styled.p`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

2018-02-16 21:10 UTC, evgenyrodionov commented on src/Footer/Button.js
> +export default props => <Button>{props.children} →</Button>;
![image](https://user-images.githubusercontent.com/775692/36329291-8e4e8836-1376-11e8-920a-cfee8cc14ee1.png)

2018-02-16 21:10 UTC, evgenyrodionov commented on src/Footer/MobileCard.js
> +const MobileCard = styled.div`
что значит мобайлкард?

2018-02-16 21:10 UTC, evgenyrodionov commented on src/Footer/MobileCard.js
> +const MobileCard = styled.div`
как бывает не мобайл?

2018-02-16 21:10 UTC, evgenyrodionov commented on src/Footer/index.js
> +import MobileCard from "./MobileCard.js";
![image](https://user-images.githubusercontent.com/775692/36329340-b8f0e4f8-1376-11e8-9977-771a9ddabfcc.png)

2018-02-16 21:10 UTC, evgenyrodionov commented on src/Footer/index.js
> +const ColTitle = styled.p`
что значит колтайтл? зачем этот префикс кол?

2018-02-16 21:10 UTC, evgenyrodionov commented on src/Footer/index.js
> +const FooterLinksList = styled.div`
если это список, то ul

2018-02-16 21:10 UTC, evgenyrodionov commented on src/Header/index.js
> +import shape from "./shape.svg";
shape? что это вообще значит?

2018-02-16 21:10 UTC, evgenyrodionov commented on src/Header/index.js
> +const Sourse = styled.div`
что такое sourse?

2018-02-16 21:10 UTC, evgenyrodionov commented on src/MobileApp/index.js
> +const Title = styled.p`
если это тайтл, то в хтмл есть заголовки от 1 до 6

2018-02-16 21:10 UTC, evgenyrodionov commented on src/MobileApp/index.js
> +const Telefon = styled.img`
phone?

2018-02-17 11:53 UTC, evgenyrodionov commented
Игнор замечаний → проверки нет

2018-02-19 17:58 UTC, closed without merging